apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: my-organiization
    provider: github
    repository: spring-boot-hello-world
  name: my-organiization-spring-boot-hello-world
spec:
  description: Imported application for my-organiization/spring-boot-hello-world
  httpCloneURL: https://github.com/my-organiization/spring-boot-hello-world.git
  org: my-organiization
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: spring-boot-hello-world
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/my-organiization/spring-boot-hello-world.git
