adminUser:
  password: local:jenkinx/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: purohitsam2020@gmail.com
  token: local:jenkinx/pipelineUser:token
  username: jenkinsbotpurohit
prow:
  hmacToken: local:jenkinx/prow:hmacToken
